<%@include file="/resources/common/res_base.inc"%>
<%@ include file="/resources/common/res_common.inc"%>
<%@ include file="/resources/common/res_grid.inc"%>
<%@include file="/resources/common/res_layout.inc"%>
<%@include file="/resources/common/res_tree.inc"%>
<%@include file="/resources/common/res_menu.inc"%>
<%@include file="/resources/common/res_pgn.inc"%>
<%@include file="/resources/common/res_tabbar.inc"%>
<script language="javascript" type="text/javascript" src="<%=request.getContextPath()%>/resources/js/sys/calendar.js"></script>
<script language="javascript" type="text/javascript" src="<%=request.getContextPath()%>/resources/js/sys/dhtmlxtree_li.js"></script>
<script language="javascript" type="text/javascript" src="<%=request.getContextPath()%>/resources/js/iframe.js"></script>
