<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/resources/component/dhtmlxLayout/dhtmlxlayout.css" />
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/resources/component/dhtmlxLayout/skins/dhtmlxlayout_<%=gridSkin %>.css">
<script language="JavaScript" type="text/javascript" src="<%=request.getContextPath()%>/resources/component/dhtmlxLayout/dhtmlxcontainer.js"></script>
<script language="JavaScript" type="text/javascript" src="<%=request.getContextPath()%>/resources/component/dhtmlxLayout/dhtmlxlayout.js"></script>
